const fs = require('fs');
const path = require('path');

/**
 * 统一处理 .conf 格式客户端
 * Surge 4/5, Shadowrocket, Surfboard 都用相同格式
 */

module.exports = function surge(config, type) {
  const lines = [];

  if (type === 'shadowrocket') {
    lines.push('# Shadowrocket Configuration');
  } else if (type === 'surfboard') {
    lines.push('# Surfboard Configuration');
  } else {
    lines.push('# Surge Configuration');
  }
  lines.push('# Generated by ConfigGen');
  lines.push('');

  // [General]
  lines.push('[General]');
  lines.push('loglevel = info');
  lines.push('allow-wifi-access = true');
  lines.push('dns-server = system,https://doh.pub/dns-query,https://dns.alidns.com/dns-query');
  lines.push('ipv6 = false');
  lines.push('interface = 0.0.0.0');
  lines.push('socks-port = 7891');
  lines.push('port = 7890');
  lines.push('');

  // [Proxy]
  lines.push('[Proxy]');
  for (const ob of (config.outbounds || [])) {
    if (['shadowsocks', 'vmess', 'vless', 'trojan', 'hysteria2'].includes(ob.type)) {
      lines.push(`${ob.tag} = ${formatProxy(ob)}`);
    }
  }
  lines.push('');

  // [Proxy Group]
  lines.push('[Proxy Group]');
  lines.push('🚀 自动选择 = select, 🔰 手动选择');
  lines.push('🔰 手动选择 = select');

  const categories = [
    ['📺 哔哩哔哩', 'bilibili'],
    ['🛑 广告拦截', 'ads'],
    ['📹 油管视频', 'youtube'],
    ['🔍 谷歌服务', 'google'],
    ['📲 电报消息', 'telegram'],
    ['🐱 Github', 'github'],
    ['🎬 流媒体', 'netflix,disney'],
    ['🎮 游戏平台', 'steam,epicgames'],
    ['💬 AI 服务', 'openai,anthropic'],
    ['🐟 漏网之鱼', 'default'],
  ];

  for (const [name, key] of categories) {
    if (key === 'default') {
      lines.push(`${name} = select, 🚀 自动选择, DIRECT`);
    } else {
      lines.push(`${name} = url-test, 🚀 自动选择, url=http://www.gstatic.com/generate_204, interval=180`);
    }
  }
  lines.push('');

  // [Rule]
  lines.push('[Rule]');

  const rules = [
    'PROCESS-NAME,com.apple.WebKit,DIRECT',
    'DOMAIN-SUFFIX,local,DIRECT',
    'DOMAIN-SUFFIX,cn,DIRECT',
    'GEOIP-CN,DIRECT',
    'DOMAIN-SUFFIX,doubleclick.net,🛑 广告拦截',
    'DOMAIN-SUFFIX,googlesyndication.com,🛑 广告拦截',
    'DOMAIN-SUFFIX,bilibili.com,📺 哔哩哔哩',
    'DOMAIN-SUFFIX,baidu.com,🔒 国内服务',
    'DOMAIN-SUFFIX,tencent.com,🔒 国内服务',
    'DOMAIN-SUFFIX,qq.com,🔒 国内服务',
    'DOMAIN-SUFFIX,youtube.com,📹 油管视频',
    'DOMAIN-SUFFIX,googlevideo.com,📹 油管视频',
    'DOMAIN-SUFFIX,google.com,🔍 谷歌服务',
    'DOMAIN-SUFFIX,telegram.org,📲 电报消息',
    'DOMAIN-SUFFIX,github.com,🐱 Github',
    'DOMAIN-SUFFIX,steampowered.com,🎮 游戏平台',
    'DOMAIN-SUFFIX,netflix.com,🎬 流媒体',
    'DOMAIN-SUFFIX,disneyplus.com,🎬 流媒体',
    'DOMAIN-SUFFIX,facebook.com,🌐 社交媒体',
    'DOMAIN-SUFFIX,twitter.com,🌐 社交媒体',
    'DOMAIN-SUFFIX,tiktok.com,🌐 社交媒体',
    'DOMAIN-SUFFIX,openai.com,💬 AI 服务',
    'DOMAIN-SUFFIX,anthropic.com,💬 AI 服务',
    'DOMAIN-SUFFIX,chatgpt.com,💬 AI 服务',
    'DOMAIN-SUFFIX,gemini.google.com,💬 AI 服务',
    'DOMAIN-SUFFIX,adobe.com,Adobe',
    'DOMAIN-SUFFIX,microsoft.com,Ⓜ️ 微软服务',
    'DOMAIN-SUFFIX,apple.com,🍏 苹果服务',
    'DOMAIN-SUFFIX,aws.amazon.com,☁️ 云服务',
    'DOMAIN-SUFFIX,azure.com,☁️ 云服务',
    'DOMAIN-SUFFIX,paypal.com,💰 金融服务',
    'DOMAIN-SUFFIX,coursera.org,📚 教育资源',
    'DOMAIN-SUFFIX,udemy.com,📚 教育资源',
    'FINAL,🐟 漏网之鱼',
  ];

  lines.push(...rules);

  return lines.join('\n');
};

function formatProxy(ob) {
  switch (ob.type) {
    case 'shadowsocks':
      return `ss,${ob.server},${ob.server_port},encrypt-method=${ob.method},password=${ob.password}`;
    case 'vless':
      let s = `vless,${ob.server},${ob.server_port},username=${ob.uuid}`;
      if (ob.tls?.reality?.enabled) {
        s += `,tls=true,reality=true`;
        if (ob.tls.reality.public_key) s += `,public-key=${ob.tls.reality.public_key}`;
        if (ob.tls.server_name) s += `,sni=${ob.tls.server_name}`;
        if (ob.flow) s += `,flow=${ob.flow}`;
      } else if (ob.tls?.enabled) {
        s += `,tls=true`;
        if (ob.tls.server_name) s += `,sni=${ob.tls.server_name}`;
      }
      return s;
    case 'vmess':
      return `vmess,${ob.server},${ob.server_port},username=${ob.uuid}`;
    case 'trojan':
      return `trojan,${ob.server},${ob.server_port},password=${ob.password}`;
    default:
      return `${ob.type},${ob.server},${ob.server_port}`;
  }
}